In [ ]:
import numpy as np

**Уровень 0:**

Задание 1

- Создайте матрицу 3 на 3, заполненную числами от 1 до 9,
- Прибавьте к ней матрицу с единицами на диагонале,
- Умножьте полученную матрицу на вектор (1, 2, 3),
- Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы,
- Посчитайте обратную матрицу к полученной в результате прибавления матрице
        

Создаем матрицу 3 на 3, заполненную числами от 1 до 9:

In [30]:
matrix = np.arange(1, 10, 1).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Прибавьте к ней матрицу с единицами на диагонали:

In [31]:
ones = np.eye(3) # единичная матрица
res_mat = matrix+ones
res_mat

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

Умножьте полученную матрицу на вектор (1, 2, 3):

In [34]:
vector =  np.array([1,2,3])
multiply = vector.dot(res_mat) #перемножаем вектор на матрицу
print(multiply)

[31. 38. 45.]


Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы:

In [36]:
transp = np.transpose(res_mat)
print(transp)

[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]


Посчитайте обратную матрицу к полученной в результате прибавления матрице:

In [37]:
invert = np.linalg.inv(res_mat)
invert

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

Проверяем перемножением обратной матрицы на исходную, чтобы получить единичную матрицу:

In [39]:
print(res_mat@invert)

[[ 1.00000000e+00 -2.22044605e-16  4.44089210e-16]
 [-1.77635684e-15  1.00000000e+00  8.88178420e-16]
 [-1.77635684e-15  4.44089210e-16  1.00000000e+00]]


**Уровень 1**

 Задание 2 
 
 Найдите собственные значения и собственные вектора матрицы:



In [43]:
m = np.array([[2, 2],
              [1, 3]])
m

array([[2, 2],
       [1, 3]])

Найдите собственные значения матрицы:

In [42]:
print(np.linalg.eigvals(m))

[1. 4.]


Найдите собственные векторы матрицы:

In [64]:
print('Собственный вектор 1:\n ', np.linalg.eig(m)[0],'\n\n', 'Собственный вектор 2:\n',np.linalg.eig(m)[1])

Собственный вектор 1:
  [1. 4.] 

 Собственный вектор 2:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Задание 2 
 
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [70]:
new_matrix = m/2 # берем исходную матрицу m из предыдущего задания и смотрим ее определитель (равный 4). Далее просто делим матрицу на 2 и получаем то, что нам нужно
print('Нужная матрица:\n', new_matrix, '\n')

print('Определитель матрицы:\n',np.linalg.det(new_matrix))

Нужная матрица:
 [[1.  1. ]
 [0.5 1.5]] 

Определитель матрицы:
 1.0
